FROM node:20-alpine

RUN apk add --no-cache postgresql-client

WORKDIR /usr/src/app

RUN mkdir ./server

COPY ./server ./server

WORKDIR /usr/src/app/server
RUN npm install

RUN npx prisma generate
RUN npm run build

EXPOSE 8080
RUN npm install pm2 -g

# CMD ["npm", "run", "pm2"]
CMD ["pm2-runtime", "npm", "--", "start"]